# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Please copy this file to your PICO device and
# rename it to settings.toml
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
Version = "0.2.1"
#
################################################
# WiFI-Configuration
#
################################################
CIRCUITPY_WIFI_SSID="<ssid>"
CIRCUITPY_WIFI_PASSWORD="<password>"
CIRCUITPY_WIFI_HOSTNAME="SolarPICO"

################################################
# GENERAL
################################################
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
LOGLEVEL = 20
UART0_TX = "GP0"
UART0_RX = "GP1"
UART1_TX = "GP4"
UART1_RX = "GP5"
UART2_TX = ""
UART2_RX = ""

################################################
# HEART-BEAT
################################################
HEARTBEAT_INTERVAL = 5000
HEARTBEAT_IDLE_INTERVAL = 150
HEARTBEAT_ERROR_INTERVAL = 500
HEARTBEAT_IDLE = 1
HEARTBEAT_ERROR_BMS = 2
HEARTBEAT_ERROR_MODBUS = 3
HEARTBEAT_ERROR_INVERTER = 4
HEARTBEAT_ERROR_WLAN = 5
HEARTBEAT_ERROR_MQTT = 6

################################################
# EPEVER - MODBUS
################################################
EPEVER_DEMO="False"
EPEVER_INTERVAL = 5000
EPEVER_VERSION = "V 0.2.2"
EPEVER_UART=1
EPEVER_BAUD=115200
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
EPEVER_LOGLEVEL=20
# below attributes should be set per connected device
EPEVER_TOPIC_KEY=["XTRA4415","TRACER"]
EPEVER_DEVICES_ID=[1,2]

################################################
# MQTT-Configuration
################################################
MQTT_BROKER_IP="<broker-ip-address>"
MQTT_PORT=1883
MQTT_PREFIX="SolarPICO"
MQTT_TOPIC="<your_topic>"
MQTT_USER="<your_user"
MQTT_PW="<users_password>"

